[project]
name = "openai-realtime-api-utils"
version = "0.1.0"
description = "openai_realtime_api_utils"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.7.1",
    "openai-agents",
    "websockets>=15.0.1",
]

[tool.uv.sources]
openai-agents = { git = "https://github.com/Daniel-Chin/openai-agents-python" }
