[project]
name = "openai-realtime-api-utils"
version = "0.1.0"
description = "openai_realtime_api_utils"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agents>=1.4.0",
    "openai>=2.7.1",
    "websockets>=15.0.1",
]
